Actividad:
  connection: doctrine
  tableName: actividad
  columns:
    idactividad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(70)
      fixed: false
      unsigned: false
      primary: false
      default: 'Actividad sin Nombre'
      notnull: true
      autoincrement: false
    fecha_entrega:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nota:
      type: integer
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_tipo_actividad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Tipoactividad:
      onDelete: CASCADE
      local: id_tipo_actividad
      foreign: idtipoactividad
    Literal:
      local: idactividad
      foreign: id_actividad
      type: many
Asistencia:
  connection: doctrine
  tableName: asistencia
  columns:
    idasistencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo_asistencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Tipoasistencia:
      onDelete: CASCADE
      local: id_tipo_asistencia
      foreign: idtipoasistencia
    UsuarioCurso:
      onDelete: CASCADE
      local: id_estudiante
      foreign: id_usuario_curso
Curso:
  connection: doctrine
  tableName: curso
  columns:
    idcurso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    paralelo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    anio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    termino:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Materia:
      onDelete: CASCADE
      local: id_materia
      foreign: idmateria
    Usuariocurso:
      local: idcurso
      foreign: id_curso
      type: many
    TipoActividad:
      local: idcurso
      foreign: id_curso
      type: many
Estudiantegrupo:
  connection: doctrine
  tableName: estudiantegrupo
  columns:
    idgrupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    Grupo:
      onDelete: CASCADE
      local: idgrupo
      foreign: idgrupo
    Usuariocurso:
      onDelete: CASCADE
      local: id_estudiante
      foreign: id_usuario
Estudianteliteral:
  connection: doctrine
  tableName: estudianteliteral
  columns:
    id_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    idliteral:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nota_literal:
      type: integer(4)
      fixed: false
      unsigned: false
      default: '0'
      autoincrement: false
    id_calificador:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: false
      autoincrement: false
    fecha:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    comentario:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: false
      autoincrement: false
  relations:
    Usuariocurso:
      onDelete: CASCADE
      local: id_estudiante
      foreign: id_usuario
    Literal:
      onDelete: CASCADE
      local: idliteral
      foreign: idliteral
Grupo:
  connection: doctrine
  tableName: grupo
  columns:
    idgrupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    numero:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      default: 'Grupo Anonimo'
      notnull: true
      autoincrement: false
  relations:
    Estudiantegrupo:
      local: idgrupo
      foreign: idgrupo
      type: many
Literal:
  connection: doctrine
  tableName: literal
  columns:
    idliteral:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_literal:
      type: string(70)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    valor_ponderacion:
      type: decimal(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_actividad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Actividad:
      onDelete: CASCADE
      local: id_actividad
      foreign: idactividad
    Estudianteliteral:
      local: idliteral
      foreign: idliteral
      type: many
Materia:
  connection: doctrine
  tableName: materia
  columns:
    idmateria:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    codigo_materia:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Curso:
      local: idmateria
      foreign: id_materia
      type: many
Rolusuario:
  connection: doctrine
  tableName: rolusuario
  columns:
    idrolusuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    UsuarioCurso:
      local: idrolusuario
      foreign: id_rol
      type: many
Tipoactividad:
  connection: doctrine
  tableName: tipoactividad
  columns:
    idtipoactividad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    valor_ponderacion:
      type: integer(10)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    parcial:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    es_extra:
      type: boolean
      primary: false
      default: false
      notnull: true
    es_grupal:
      type: boolean
      primary: false
      default: true
      notnull: true
    tiene_factor_1:
      type: boolean
      primary: false
      default: false
      notnull: true
    tiene_factor_2:
      type: boolean
      primary: false
      default: false
      notnull: true
  relations:
    Actividad:
      local: idtipoactividad
      foreign: id_tipo_actividad
      type: many
    Curso:
      onDelete: CASCADE
      local: id_curso
      foreign: idcurso
      
Tipoasistencia:
  connection: doctrine
  tableName: tipoasistencia
  columns:
    idtipoasistencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Asistencia:
      local: idtipoasistencia
      foreign: id_tipo_asistencia
      type: many
Usuario:
  connection: doctrine
  tableName: usuario
  columns:
    idusuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    usuario_espol:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    apellido:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mail:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    matricula:
      type: string(45)
      primary: false
      notnull: false
      autoincrement: false
    cedula:
      type: string(45)
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Usuariocurso:
      
      local: idusuario
      foreign: id_usuario
      type: many
UsuarioCurso:
  connection: doctrine
  tableName: usuariocurso
  columns:
    id_usuario_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    id_rol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
  relations:
    Curso:
      onDelete: CASCADE
      local: id_curso
      foreign: idcurso
    Usuario:
      onDelete: CASCADE
      local: id_usuario
      foreign: idusuario
    Estudiantegrupo:
      local: id_usuario_curso
      foreign: id_estudiante
      type: many
    Estudianteliteral:
      local: id_usuario
      foreign: id_estudiante
      type: many
    Rolusuario:
      onDelete: CASCADE
      local: id_rol
      foreign: idrolusuario
    Asistencia:
      local: id_usuario_curso
      foreign: idasistencia
      type: many
