Actividad:
  connection: doctrine
  tableName: actividad
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_categoria:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha:
      type: TIMESTAMP
      notnull: true
    id_tipo_calificacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Tipocalificacion:
      local: id_tipo_calificacion
      foreign: id
    Categoria:
      local: id_categoria
      foreign: id
    Item:
      local: id
      foreign: id_actividad
      type: many
      
Asistencia:
  connection: doctrine
  tableName: asistencia
  columns:
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario:
      type: string(45)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fecha:
      type: TIMESTAMP
      notnull: true
    valor:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      
  relations:
    Curso:
      local: id_curso
      foreign: id
    Usuario:
      local: id_usuario
      foreign: id
      
Ayudantecurso:
  connection: doctrine
  tableName: ayudantecurso
  columns:
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario:
      type: string(45)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    estado:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Curso:
      local: id_curso
      foreign: id
    Usuario:
      local: id_usuario
      foreign: id
      
Calificacion:
  connection: doctrine
  tableName: calificacion
  columns:
    id_estudiante:
      type: string(45)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_item:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    valor:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha:
      type: TIMESTAMP
      notnull: true
      
  relations:
    Usuario:
      local: id_usuario
      foreign: id
    Item:
      local: id_item
      foreign: id
      
Categoria:
  connection: doctrine
  tableName: categoria
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    periodo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    porcentaje:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo_categoria:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Actividad:
      local: id
      foreign: id_categoria
      type: many
    Tipocategoria:
      local: id_tipo_categoria
      foreign: id
    Curso:
      local: id_curso
      foreign: id
Curso:
  connection: doctrine
  tableName: curso
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    anio:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    termino:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_materia:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    paralelo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    profesor:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    factor_asistencia1:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    factor_asistencia2:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Categoria:
      local: id
      foreign: id_curso
      type: many
    Materia:
      local: id_materia
      foreign: id_codigo
    Asistencia:
      local: id
      foreign: id_curso
      type: many
    Usuario:
      local: profesor
      foreign: id
    Ayudantecurso:
      local: id
      foreign: id_curso
      type: many
    Estudiantecurso:
      local: id
      foreign: id_curso
      type: many
    Grupo:
      local: id
      foreign: id_curso
      type: many
Estudiantecurso:
  connection: doctrine
  tableName: estudiantecurso
  columns:
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario:
      type: string(45)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      
  relations:
     Curso:
       local: id_curso
       foreign: id
     Usuario: 
       local: id_usuario
       foreign: id
     Grupo:
       local: id_grupo
       foreign: id
Grupo:
  connection: doctrine
  tableName: grupo
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    numero:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      
  relations:
    Curso:
      local: id_curso
      foreign: id
    Estudiantecurso:
      local: id
      foreign: id_grupo
      type: many
      
Item:
  connection: doctrine
  tableName: item
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_actividad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    literal:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(400)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    valor_max:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Actividad: 
      local: id_actividad
      foreign: id
    Calificacion:
      local: id_item
      foreign: id
      type: many
Logs:
  connection: doctrine
  tableName: logs
  columns:
    id_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_item:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nota_anterior:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nota_nueva:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha:
      type: TIMESTAMP
      notnull: true
    
Materia:
  connection: doctrine
  tableName: materia
  columns:
    id_codigo:
      type: string(50)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(400)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Curso:
      local: id_codigo
      foreign: id_materia
      type: many
Rolusuario:
  connection: doctrine
  tableName: rolusuario
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    detalle:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      default: ' '
      notnull: true
      autoincrement: false
      
  relations:
    Usuario:
      local: id
      foreign: id_rol
      type: many
      
Tipocalificacion:
  connection: doctrine
  tableName: tipocalificacion
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    detalle:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      default: ' '
      notnull: true
      autoincrement: false
  relations:
    Actividad:
      type: many
      local: id
      foreign: id_tipo_calificacion
      
Tipocategoria:
  connection: doctrine
  tableName: tipocategoria
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    detalle:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      default: ' '
      notnull: true
      autoincrement: false
  relations:
    Categoria:
      local: id
      foreign: id_tipo_categoria
      type: many
      
      
Usuario:
  connection: doctrine
  tableName: usuario
  columns:
    id:
      type: string(45)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mail:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_rol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Rolusuario:
      local: id_rol
      foreign: id
    Asistencia:
      local: id
      foreign: id_usuario
      type: many
    Ayudantecurso:
      local: id
      foreign: id_usuario
      type: many
    Estudiantecurso:
      local: id
      foreign: id_usuario
      type: many
    Calificacion:
      local: id
      foreign: id_usuario
      type: many
    Curso:
      local: id
      foreign: profesor
      type: many