<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipoasistencia', 'doctrine');

/**
 * BaseTipoasistencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoasistencia
 * @property string $nombre
 * @property Doctrine_Collection $Asistencia
 * 
 * @method integer             getIdtipoasistencia() Returns the current record's "idtipoasistencia" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method Doctrine_Collection getAsistencia()       Returns the current record's "Asistencia" collection
 * @method Tipoasistencia      setIdtipoasistencia() Sets the current record's "idtipoasistencia" value
 * @method Tipoasistencia      setNombre()           Sets the current record's "nombre" value
 * @method Tipoasistencia      setAsistencia()       Sets the current record's "Asistencia" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoasistencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipoasistencia');
        $this->hasColumn('idtipoasistencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Asistencia', array(
             'local' => 'idtipoasistencia',
             'foreign' => 'id_tipo_asistencia'));
    }
}