<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rolusuario', 'doctrine');

/**
 * BaseRolusuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idrolusuario
 * @property string $nombre
 * @property Doctrine_Collection $UsuarioCurso
 * 
 * @method integer             getIdrolusuario() Returns the current record's "idrolusuario" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Doctrine_Collection getUsuarioCurso() Returns the current record's "UsuarioCurso" collection
 * @method Rolusuario          setIdrolusuario() Sets the current record's "idrolusuario" value
 * @method Rolusuario          setNombre()       Sets the current record's "nombre" value
 * @method Rolusuario          setUsuarioCurso() Sets the current record's "UsuarioCurso" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRolusuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rolusuario');
        $this->hasColumn('idrolusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UsuarioCurso', array(
             'local' => 'idrolusuario',
             'foreign' => 'id_rol'));
    }
}