<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioCurso', 'doctrine');

/**
 * BaseUsuarioCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario_curso
 * @property integer $id_curso
 * @property integer $id_usuario
 * @property integer $id_rol
 * @property Curso $Curso
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Estudiantegrupo
 * @property Doctrine_Collection $Estudianteliteral
 * @property Rolusuario $Rolusuario
 * @property Doctrine_Collection $Asistencia
 * 
 * @method integer             getIdUsuarioCurso()    Returns the current record's "id_usuario_curso" value
 * @method integer             getIdCurso()           Returns the current record's "id_curso" value
 * @method integer             getIdUsuario()         Returns the current record's "id_usuario" value
 * @method integer             getIdRol()             Returns the current record's "id_rol" value
 * @method Curso               getCurso()             Returns the current record's "Curso" value
 * @method Usuario             getUsuario()           Returns the current record's "Usuario" value
 * @method Doctrine_Collection getEstudiantegrupo()   Returns the current record's "Estudiantegrupo" collection
 * @method Doctrine_Collection getEstudianteliteral() Returns the current record's "Estudianteliteral" collection
 * @method Rolusuario          getRolusuario()        Returns the current record's "Rolusuario" value
 * @method Doctrine_Collection getAsistencia()        Returns the current record's "Asistencia" collection
 * @method UsuarioCurso        setIdUsuarioCurso()    Sets the current record's "id_usuario_curso" value
 * @method UsuarioCurso        setIdCurso()           Sets the current record's "id_curso" value
 * @method UsuarioCurso        setIdUsuario()         Sets the current record's "id_usuario" value
 * @method UsuarioCurso        setIdRol()             Sets the current record's "id_rol" value
 * @method UsuarioCurso        setCurso()             Sets the current record's "Curso" value
 * @method UsuarioCurso        setUsuario()           Sets the current record's "Usuario" value
 * @method UsuarioCurso        setEstudiantegrupo()   Sets the current record's "Estudiantegrupo" collection
 * @method UsuarioCurso        setEstudianteliteral() Sets the current record's "Estudianteliteral" collection
 * @method UsuarioCurso        setRolusuario()        Sets the current record's "Rolusuario" value
 * @method UsuarioCurso        setAsistencia()        Sets the current record's "Asistencia" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuariocurso');
        $this->hasColumn('id_usuario_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_rol', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Curso', array(
             'local' => 'id_curso',
             'foreign' => 'idcurso',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'idusuario',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Estudiantegrupo', array(
             'local' => 'id_usuario_curso',
             'foreign' => 'id_estudiante'));

        $this->hasMany('Estudianteliteral', array(
             'local' => 'id_usuario',
             'foreign' => 'id_estudiante'));

        $this->hasOne('Rolusuario', array(
             'local' => 'id_rol',
             'foreign' => 'idrolusuario',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Asistencia', array(
             'local' => 'id_usuario_curso',
             'foreign' => 'idasistencia'));
    }
}