<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idusuario
 * @property string $usuario_espol
 * @property string $nombre
 * @property string $apellido
 * @property string $mail
 * @property string $matricula
 * @property string $cedula
 * @property Doctrine_Collection $UsuarioCurso
 * 
 * @method integer             getIdusuario()     Returns the current record's "idusuario" value
 * @method string              getUsuarioEspol()  Returns the current record's "usuario_espol" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getApellido()      Returns the current record's "apellido" value
 * @method string              getMail()          Returns the current record's "mail" value
 * @method string              getMatricula()     Returns the current record's "matricula" value
 * @method string              getCedula()        Returns the current record's "cedula" value
 * @method Doctrine_Collection getUsuarioCurso()  Returns the current record's "UsuarioCurso" collection
 * @method Usuario             setIdusuario()     Sets the current record's "idusuario" value
 * @method Usuario             setUsuarioEspol()  Sets the current record's "usuario_espol" value
 * @method Usuario             setNombre()        Sets the current record's "nombre" value
 * @method Usuario             setApellido()      Sets the current record's "apellido" value
 * @method Usuario             setMail()          Sets the current record's "mail" value
 * @method Usuario             setMatricula()     Sets the current record's "matricula" value
 * @method Usuario             setCedula()        Sets the current record's "cedula" value
 * @method Usuario             setUsuarioCurso()  Sets the current record's "UsuarioCurso" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_espol', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('apellido', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('mail', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('matricula', 'string', 45, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('cedula', 'string', 45, array(
             'type' => 'string',
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UsuarioCurso', array(
             'local' => 'idusuario',
             'foreign' => 'id_usuario'));
    }
}