<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Actividad', 'doctrine');

/**
 * BaseActividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idactividad
 * @property string $nombre
 * @property integer $nota
 * @property timestamp $fecha_entrega
 * @property integer $id_tipo_actividad
 * @property Tipoactividad $Tipoactividad
 * @property Doctrine_Collection $Literal
 * 
 * @method integer             getIdactividad()       Returns the current record's "idactividad" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method integer             getNota()              Returns the current record's "nota" value
 * @method timestamp           getFechaEntrega()      Returns the current record's "fecha_entrega" value
 * @method integer             getIdTipoActividad()   Returns the current record's "id_tipo_actividad" value
 * @method Tipoactividad       getTipoactividad()     Returns the current record's "Tipoactividad" value
 * @method Doctrine_Collection getLiteral()           Returns the current record's "Literal" collection
 * @method Actividad           setIdactividad()       Sets the current record's "idactividad" value
 * @method Actividad           setNombre()            Sets the current record's "nombre" value
 * @method Actividad           setNota()              Sets the current record's "nota" value
 * @method Actividad           setFechaEntrega()      Sets the current record's "fecha_entrega" value
 * @method Actividad           setIdTipoActividad()   Sets the current record's "id_tipo_actividad" value
 * @method Actividad           setTipoactividad()     Sets the current record's "Tipoactividad" value
 * @method Actividad           setLiteral()           Sets the current record's "Literal" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actividad');
        $this->hasColumn('idactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Actividad sin Nombre',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('fecha_entrega', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_tipo_actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipoactividad', array(
             'local' => 'id_tipo_actividad',
             'foreign' => 'idtipoactividad',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Literal', array(
             'local' => 'idactividad',
             'foreign' => 'id_actividad'));
    }
}