<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipoactividad', 'doctrine');

/**
 * BaseTipoactividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoactividad
 * @property integer $id_curso
 * @property integer $valor_ponderacion
 * @property string $nombre
 * @property integer $parcial
 * @property boolean $es_extra
 * @property boolean $es_grupal
 * @property boolean $tiene_factor_1
 * @property boolean $tiene_factor_2
 * @property Doctrine_Collection $Actividad
 * @property Curso $Curso
 * 
 * @method integer             getIdtipoactividad()   Returns the current record's "idtipoactividad" value
 * @method integer             getIdCurso()           Returns the current record's "id_curso" value
 * @method integer             getValorPonderacion()  Returns the current record's "valor_ponderacion" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method integer             getParcial()           Returns the current record's "parcial" value
 * @method boolean             getEsExtra()           Returns the current record's "es_extra" value
 * @method boolean             getEsGrupal()          Returns the current record's "es_grupal" value
 * @method boolean             getTieneFactor1()      Returns the current record's "tiene_factor_1" value
 * @method boolean             getTieneFactor2()      Returns the current record's "tiene_factor_2" value
 * @method Doctrine_Collection getActividad()         Returns the current record's "Actividad" collection
 * @method Curso               getCurso()             Returns the current record's "Curso" value
 * @method Tipoactividad       setIdtipoactividad()   Sets the current record's "idtipoactividad" value
 * @method Tipoactividad       setIdCurso()           Sets the current record's "id_curso" value
 * @method Tipoactividad       setValorPonderacion()  Sets the current record's "valor_ponderacion" value
 * @method Tipoactividad       setNombre()            Sets the current record's "nombre" value
 * @method Tipoactividad       setParcial()           Sets the current record's "parcial" value
 * @method Tipoactividad       setEsExtra()           Sets the current record's "es_extra" value
 * @method Tipoactividad       setEsGrupal()          Sets the current record's "es_grupal" value
 * @method Tipoactividad       setTieneFactor1()      Sets the current record's "tiene_factor_1" value
 * @method Tipoactividad       setTieneFactor2()      Sets the current record's "tiene_factor_2" value
 * @method Tipoactividad       setActividad()         Sets the current record's "Actividad" collection
 * @method Tipoactividad       setCurso()             Sets the current record's "Curso" value
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoactividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipoactividad');
        $this->hasColumn('idtipoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valor_ponderacion', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('nombre', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('parcial', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('es_extra', 'boolean', null, array(
             'type' => 'boolean',
             'primary' => false,
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('es_grupal', 'boolean', null, array(
             'type' => 'boolean',
             'primary' => false,
             'default' => true,
             'notnull' => true,
             ));
        $this->hasColumn('tiene_factor_1', 'boolean', null, array(
             'type' => 'boolean',
             'primary' => false,
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('tiene_factor_2', 'boolean', null, array(
             'type' => 'boolean',
             'primary' => false,
             'default' => false,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Actividad', array(
             'local' => 'idtipoactividad',
             'foreign' => 'id_tipo_actividad'));

        $this->hasOne('Curso', array(
             'local' => 'id_curso',
             'foreign' => 'idcurso'));
    }
}