<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ayudantecurso', 'doctrine');

/**
 * BaseAyudantecurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_curso
 * @property string $id_usuario
 * @property integer $estado
 * @property Curso $Curso
 * @property Usuario $Usuario
 * 
 * @method integer       getIdCurso()    Returns the current record's "id_curso" value
 * @method string        getIdUsuario()  Returns the current record's "id_usuario" value
 * @method integer       getEstado()     Returns the current record's "estado" value
 * @method Curso         getCurso()      Returns the current record's "Curso" value
 * @method Usuario       getUsuario()    Returns the current record's "Usuario" value
 * @method Ayudantecurso setIdCurso()    Sets the current record's "id_curso" value
 * @method Ayudantecurso setIdUsuario()  Sets the current record's "id_usuario" value
 * @method Ayudantecurso setEstado()     Sets the current record's "estado" value
 * @method Ayudantecurso setCurso()      Sets the current record's "Curso" value
 * @method Ayudantecurso setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAyudantecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ayudantecurso');
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Curso', array(
             'local' => 'id_curso',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id'));
    }
}