<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Categoria', 'doctrine');

/**
 * BaseCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_curso
 * @property string $nombre
 * @property integer $periodo
 * @property integer $porcentaje
 * @property integer $id_tipo_categoria
 * @property Doctrine_Collection $Actividad
 * @property Tipocategoria $Tipocategoria
 * @property Curso $Curso
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getIdCurso()           Returns the current record's "id_curso" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method integer             getPeriodo()           Returns the current record's "periodo" value
 * @method integer             getPorcentaje()        Returns the current record's "porcentaje" value
 * @method integer             getIdTipoCategoria()   Returns the current record's "id_tipo_categoria" value
 * @method Doctrine_Collection getActividad()         Returns the current record's "Actividad" collection
 * @method Tipocategoria       getTipocategoria()     Returns the current record's "Tipocategoria" value
 * @method Curso               getCurso()             Returns the current record's "Curso" value
 * @method Categoria           setId()                Sets the current record's "id" value
 * @method Categoria           setIdCurso()           Sets the current record's "id_curso" value
 * @method Categoria           setNombre()            Sets the current record's "nombre" value
 * @method Categoria           setPeriodo()           Sets the current record's "periodo" value
 * @method Categoria           setPorcentaje()        Sets the current record's "porcentaje" value
 * @method Categoria           setIdTipoCategoria()   Sets the current record's "id_tipo_categoria" value
 * @method Categoria           setActividad()         Sets the current record's "Actividad" collection
 * @method Categoria           setTipocategoria()     Sets the current record's "Tipocategoria" value
 * @method Categoria           setCurso()             Sets the current record's "Curso" value
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('periodo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('porcentaje', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Actividad', array(
             'local' => 'id',
             'foreign' => 'id_categoria'));

        $this->hasOne('Tipocategoria', array(
             'local' => 'id_tipo_categoria',
             'foreign' => 'id'));

        $this->hasOne('Curso', array(
             'local' => 'id_curso',
             'foreign' => 'id'));
    }
}