<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Item', 'doctrine');

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_actividad
 * @property integer $literal
 * @property string $nombre
 * @property integer $valor_max
 * @property Actividad $Actividad
 * @property Doctrine_Collection $Calificacion
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getIdActividad()  Returns the current record's "id_actividad" value
 * @method integer             getLiteral()      Returns the current record's "literal" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method integer             getValorMax()     Returns the current record's "valor_max" value
 * @method Actividad           getActividad()    Returns the current record's "Actividad" value
 * @method Doctrine_Collection getCalificacion() Returns the current record's "Calificacion" collection
 * @method Item                setId()           Sets the current record's "id" value
 * @method Item                setIdActividad()  Sets the current record's "id_actividad" value
 * @method Item                setLiteral()      Sets the current record's "literal" value
 * @method Item                setNombre()       Sets the current record's "nombre" value
 * @method Item                setValorMax()     Sets the current record's "valor_max" value
 * @method Item                setActividad()    Sets the current record's "Actividad" value
 * @method Item                setCalificacion() Sets the current record's "Calificacion" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('literal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 400, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 400,
             ));
        $this->hasColumn('valor_max', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Actividad', array(
             'local' => 'id_actividad',
             'foreign' => 'id'));

        $this->hasMany('Calificacion', array(
             'local' => 'id_item',
             'foreign' => 'id'));
    }
}