<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Asistencia', 'doctrine');

/**
 * BaseAsistencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_curso
 * @property string $id_usuario
 * @property TIMESTAMP $fecha
 * @property string $valor
 * @property Curso $Curso
 * @property Usuario $Usuario
 * 
 * @method integer    getIdCurso()    Returns the current record's "id_curso" value
 * @method string     getIdUsuario()  Returns the current record's "id_usuario" value
 * @method TIMESTAMP  getFecha()      Returns the current record's "fecha" value
 * @method string     getValor()      Returns the current record's "valor" value
 * @method Curso      getCurso()      Returns the current record's "Curso" value
 * @method Usuario    getUsuario()    Returns the current record's "Usuario" value
 * @method Asistencia setIdCurso()    Sets the current record's "id_curso" value
 * @method Asistencia setIdUsuario()  Sets the current record's "id_usuario" value
 * @method Asistencia setFecha()      Sets the current record's "fecha" value
 * @method Asistencia setValor()      Sets the current record's "valor" value
 * @method Asistencia setCurso()      Sets the current record's "Curso" value
 * @method Asistencia setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsistencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia');
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('fecha', 'TIMESTAMP', null, array(
             'type' => 'TIMESTAMP',
             'notnull' => true,
             ));
        $this->hasColumn('valor', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Curso', array(
             'local' => 'id_curso',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id'));
    }
}