<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipocalificacion', 'doctrine');

/**
 * BaseTipocalificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $detalle
 * @property Doctrine_Collection $Actividad
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getDetalle()   Returns the current record's "detalle" value
 * @method Doctrine_Collection getActividad() Returns the current record's "Actividad" collection
 * @method Tipocalificacion    setId()        Sets the current record's "id" value
 * @method Tipocalificacion    setNombre()    Sets the current record's "nombre" value
 * @method Tipocalificacion    setDetalle()   Sets the current record's "detalle" value
 * @method Tipocalificacion    setActividad() Sets the current record's "Actividad" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipocalificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipocalificacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('detalle', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Actividad', array(
             'local' => 'id',
             'foreign' => 'id_tipo_calificacion'));
    }
}