<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Actividad', 'doctrine');

/**
 * BaseActividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_categoria
 * @property string $nombre
 * @property TIMESTAMP $fecha
 * @property integer $id_tipo_calificacion
 * @property Tipocalificacion $Tipocalificacion
 * @property Categoria $Categoria
 * @property Doctrine_Collection $Item
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getIdCategoria()          Returns the current record's "id_categoria" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method TIMESTAMP           getFecha()                Returns the current record's "fecha" value
 * @method integer             getIdTipoCalificacion()   Returns the current record's "id_tipo_calificacion" value
 * @method Tipocalificacion    getTipocalificacion()     Returns the current record's "Tipocalificacion" value
 * @method Categoria           getCategoria()            Returns the current record's "Categoria" value
 * @method Doctrine_Collection getItem()                 Returns the current record's "Item" collection
 * @method Actividad           setId()                   Sets the current record's "id" value
 * @method Actividad           setIdCategoria()          Sets the current record's "id_categoria" value
 * @method Actividad           setNombre()               Sets the current record's "nombre" value
 * @method Actividad           setFecha()                Sets the current record's "fecha" value
 * @method Actividad           setIdTipoCalificacion()   Sets the current record's "id_tipo_calificacion" value
 * @method Actividad           setTipocalificacion()     Sets the current record's "Tipocalificacion" value
 * @method Actividad           setCategoria()            Sets the current record's "Categoria" value
 * @method Actividad           setItem()                 Sets the current record's "Item" collection
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actividad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('fecha', 'TIMESTAMP', null, array(
             'type' => 'TIMESTAMP',
             'notnull' => true,
             ));
        $this->hasColumn('id_tipo_calificacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipocalificacion', array(
             'local' => 'id_tipo_calificacion',
             'foreign' => 'id'));

        $this->hasOne('Categoria', array(
             'local' => 'id_categoria',
             'foreign' => 'id'));

        $this->hasMany('Item', array(
             'local' => 'id',
             'foreign' => 'id_actividad'));
    }
}