<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudiantecurso', 'doctrine');

/**
 * BaseEstudiantecurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_curso
 * @property string $id_usuario
 * @property integer $id_grupo
 * @property Curso $Curso
 * @property Usuario $Usuario
 * @property Grupo $Grupo
 * 
 * @method integer         getIdCurso()    Returns the current record's "id_curso" value
 * @method string          getIdUsuario()  Returns the current record's "id_usuario" value
 * @method integer         getIdGrupo()    Returns the current record's "id_grupo" value
 * @method Curso           getCurso()      Returns the current record's "Curso" value
 * @method Usuario         getUsuario()    Returns the current record's "Usuario" value
 * @method Grupo           getGrupo()      Returns the current record's "Grupo" value
 * @method Estudiantecurso setIdCurso()    Sets the current record's "id_curso" value
 * @method Estudiantecurso setIdUsuario()  Sets the current record's "id_usuario" value
 * @method Estudiantecurso setIdGrupo()    Sets the current record's "id_grupo" value
 * @method Estudiantecurso setCurso()      Sets the current record's "Curso" value
 * @method Estudiantecurso setUsuario()    Sets the current record's "Usuario" value
 * @method Estudiantecurso setGrupo()      Sets the current record's "Grupo" value
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     ABEJJA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiantecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiantecurso');
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Curso', array(
             'local' => 'id_curso',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario',
             'foreign' => 'id'));

        $this->hasOne('Grupo', array(
             'local' => 'id_grupo',
             'foreign' => 'id'));
    }
}