# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

homepage:
  url:   /
  param: { module: default, action: index }

default_module:
  url:    /:module
  param:  { module: :module , action: index }
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /Estudiantes
#  param: { module: Estudiantes, action: index }

default:
  url:   /:module/:action/*
#  
login:
  url:   Inicio/login
  
logout:
  url:   Inicio/logout
#
#inicio:
#  url:   /Inicio
#  param: { module: Inicio, action: index }
