## YAML Template.
---
##
# Modulo: Inicio
# @author Efrain Astudillo

loginSuccess:
  stylesheets: [layout/estiloLogin.css,modulo/Inicio/login.css]
  
  javascripts:    [login.js]
  
  has_layout:     true
  layout:         layout_login
  
LoginSuccess:
  stylesheets: [layout/estiloLogin.css,modulo/Inicio/login.css]
  
  javascripts:    [login.js]
  
  has_layout:     true
  layout:         layout_login
  
adminloginSuccess:
  stylesheets: [layout/estiloLogin.css,modulo/Inicio/login.css]
  
  javascripts:    [login.js]
  
  has_layout:     true
  layout:         layout_login
AdminloginSuccess:
  stylesheets: [layout/estiloLogin.css,modulo/Inicio/login.css]
  
  javascripts:    [login.js]
  
  has_layout:     true
  layout:         layout_login