## YAML Template.
---
indexSuccess:
  stylesheets:    [modulo/estudiante/estudiante.css,overcast/jquery-ui-1.8.22.custom.css]
  
  javascripts:    [jquery.ui.core.min.js,jquery.ui.widget.min.js,jquery.ui.datepicker.min.js,asistencia.js]
  
  has_layout:     true
  layout:         layout