## YAML Template.
newLiteralSuccess:
  
  has_layout:     true
  layout:         layout_popup
newliteralSuccess:
  
  has_layout:     true
  layout:         layout_popup

indexSuccess:
 
  stylesheets:    [modulo/actividad/actividad.css]
  javascripts:    [actividad.js]
  has_layout:     true
  layout:         layout

newViewSuccess:

  stylesheets:    [modulo/actividad/actividad.css]
  javascripts:    [actividad.js,jquery.ui.core.min.js,jquery.ui.widget.min.js,jquery.ui.datepicker.min.js,asistencia.js]
  has_layout:     true
  layout:         layout
  
actividadSuccess:
  stylesheets:    [modulo/actividad/actividad.css]
  javascripts:    [tipoactividad.js]
  has_layout:     true
  layout:         layout