<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/13 20:36:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=calpespol',
  'username' => 'developer',
  'password' => 'developer',
  'name' => 'doctrine',
)),);
