indexSuccess:
  stylesheets: [modulo/grupo/grupo.css,modulo/grupo/demo_table.css,modulo/grupo/jquery.alerts.css]
  
  javascripts:    [grupo.js,jquery.dataTables.js,jquery.alerts.js]
  
  has_layout:     true
  layout:         layout
  
IndexSuccess:
  stylesheets: [modulo/grupo/grupo.css,modulo/grupo/demo_table.css,modulo/grupo/jquery.alerts.css]
  
  javascripts:    [grupo.js,jquery.dataTables.js,jquery.alerts.js]
  
  has_layout:     true
  layout:         layout
  
newSuccess:
  stylesheets: [modulo/grupo/grupo.css,modulo/grupo/demo_table.css,modulo/grupo/jquery.alerts.css]
  
  javascripts:    [grupo.js,jquery.dataTables.js,jquery.alerts.js]
  
  has_layout:     true
  layout:         layout
  
NewSuccess:
  stylesheets: [modulo/grupo/grupo.css,modulo/grupo/demo_table.css,modulo/grupo/jquery.alerts.css]
  
  javascripts:    [grupo.js,jquery.dataTables.js,jquery.alerts.js]
  
  has_layout:     true
  layout:         layout