<?php

/**
 * ActividadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActividadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActividadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Actividad');
    }
}