<?php

/**
 * AyudantecursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AyudantecursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AyudantecursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ayudantecurso');
    }
}