<?php

/**
 * CalificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CalificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Calificacion');
    }
}