<?php

/**
 * TipocategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipocategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipocategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipocategoria');
    }
}