<?php

/**
 * TipocalificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipocalificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipocalificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipocalificacion');
    }
}