<?php

/**
 * Curso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Curso extends BaseCurso
{
    public static function getParalelosOfUsuarioByMateria($materia,$iduser)
    {
        $q = Doctrine_Query::create()
        ->select("*")
        ->from('Curso c')
                ->innerJoin("c.Materia m ON c.id_materia=m.idmateria")
                ->innerJoin("c.UsuarioCurso uc ON uc.id_curso=c.idcurso")
                ->where("m.nombre=?",$materia)
                ->andWhere("uc.id_usuario=?",$iduser)
                ->execute();
        return $q;
    }
}