<?php

/**
 * EstudiantegrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudiantegrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudiantegrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudiantegrupo');
    }
}