<?php

/**
 * EstudianteliteralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudianteliteralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudianteliteralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudianteliteral');
    }
}