<?php

/**
 * LiteralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LiteralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LiteralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Literal');
    }
}