<?php

/**
 * Literal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Literal extends BaseLiteral
{
//    public static function getLiterales()
//    {
//        $q = Doctrine_Query::create()
//        ->from('Literal l');
//        return $q->execute();
//    }
    
    
        public static function getLiterales()
    {
        $q = Doctrine_Query::create()
        ->select('*')   
        ->from('literal l')
        ->where('l.id_actividad=?', '2');
        return $q->execute();  
    }
    
    
}