<?php

/**
 * MateriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MateriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MateriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Materia');
    }
}