<?php

/**
 * Materia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Materia extends BaseMateria
{

    public static function getMaterias()
    {
        $q = Doctrine_Query::create()
        ->from('Materia m');
        return $q->execute();
    }
}