<?php

/**
 * Rolusuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CALPESPOL
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rolusuario extends BaseRolusuario
{
     /**
      *
      * @param type $rol
      * @return type 
      */
     public static function getRolUsuario($rol){
         $rol=Doctrine_Query::create()
                 ->from("Rolusuario u")
                 ->where("u.nombre=?",$rol)
                 ->fetchOne();
         return $rol;
     }
}