<?php

/**
 * TipoactividadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoactividadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoactividadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipoactividad');
    }
}