<?php

/**
 * TipoasistenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoasistenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoasistenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipoasistencia');
    }
}