<?php

/**
 * UsuarioCursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioCursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioCursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioCurso');
    }
}