<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/13 20:27:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=calpespol',
  'username' => 'root',
  'password' => 281407,
  'name' => 'doctrine',
)),);
